### ISSUE TITLE
Coordinates are not beeing emitted on address create

### ISSUE THREAD

**Issue by Schweriner** [undkonsorten/addressmgmt#3]
This is caused by the Address Model which has its $latitude and $longitude attribute declared without and a default value. When creating a new address, these properties are instanciated with "NULL". This causes the condition within in the AddressLocatorService not to recognize the address for an update.

The properties are NULL so `=== ''` does not work.
if($isNew && $address->getLatitude() === '' && $address->getLongitude() === ''){

I will prepare a Pull request for this.

**Comment by Starkmann** [comment]
Deleted master today, that is why the pull request was closed.

This commit fixes this issue: [Schweriner](https://github.com/Schweriner)

Thanks for the report.
